name: Flutter CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test_and_analyze:
    name: Analyze and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Instalar dependências
        run: flutter pub get

      - name: Verificar formatação de código
        run: dart format --output=none --set-exit-if-changed .

      - name: Análise estática (Linter)
        run: flutter analyze

      - name: Executar testes unitários e de widget
        run: flutter test